name: PR Auto Merge
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - master
      - main
      - rc
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/wait-on-check
      - name: Wait for CI workflow to succeed
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          check-name: 'validation'
          repo-token: ${{ secrets.PAT }}
          wait-interval: 10

      # https://github.com/marketplace/actions/list-files-in-pull-request
      - uses: ankitjain28may/list-files-in-pr@v1.0
        id: list-files
        with:
          githubToken: ${{ secrets.PAT }}
          outputFormat: 'space-delimited'

      # https://github.com/marketplace/actions/merge-pull-requests-automerge-action
      - id: automerge
        if: ${{  steps.list-files.outputs.pullRequestFiles == 'composer.lock' }}
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.PAT }}"
          MERGE_LABELS: "dependencies"
          MERGE_REMOVE_LABELS: "automerge"
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_FORKS: "false"
          MERGE_RETRIES: "3"
          MERGE_RETRY_SLEEP: "10000"
          MERGE_REQUIRED_APPROVALS: "0"
          UPDATE_LABELS: ""
          UPDATE_METHOD: "merge"
          PULL_REQUEST: ${{ github.event.pull_request.number }}
