name: PR Auto Merge
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - master
      - main
      - rc
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/list-files-in-pull-request
      - uses: ankitjain28may/list-files-in-pr@v1.0
        id: can-auto-merge
        with:
          githubToken: ${{ secrets.PAT }}
          outputFormat: 'json'

      - id: check-files
        run: |
          CAN_MERGE=0
          FILES=${{ steps.list-files.outputs.pullRequestFiles }}
          if [[ "$FILES" != '' ]]
          then
            echo "can-merge=$CAN_MERGE" >> "$GITHUB_OUTPUT"
            echo "No files. Res: can-merge=$CAN_MERGE"
            exit 0
          fi

          LEN=${#FILES[@]}
          if [[ "$LEN" -ne 1 ]]
          then
            echo "can-merge=$CAN_MERGE" >> "$GITHUB_OUTPUT"
            echo "No files. Res: can-merge=$CAN_MERGE"
            exit 0
          fi

          FILE=${#FILES[0]}
          [[ "$FILE" == 'composer.lock' ]] && CAN_MERGE=1 || CAN_MERGE=0
          echo "can-merge=$CAN_MERGE" >> "$GITHUB_OUTPUT"
          echo "file: $FILE"
          echo "can-merge=$CAN_MERGE"

      - id: automerge
        if: ${{ steps.check-files.outputs.can-merge == '1' }}
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.PAT }}"
          MERGE_LABELS: "dependencies"
          MERGE_REMOVE_LABELS: "automerge"
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_FORKS: "false"
          MERGE_RETRIES: "3"
          MERGE_RETRY_SLEEP: "10000"
          MERGE_REQUIRED_APPROVALS: "0"
          UPDATE_LABELS: ""
          UPDATE_METHOD: "merge"
          PULL_REQUEST: ${{ github.event.pull_request.number }}
