name: CI

on:
    pull_request:
    push:
        branches:
            - main
            - develop
            - feature/[a-z]+-[0-9]+/dev-*
    workflow_dispatch:


jobs:
  validation:
    name: "composer install and validate"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2

      - name: Composer validate
        run: composer validate

      - name: Composer version
        run: composer --version

      - name: Composer install
        run: composer install

  upload-artifacts:
    name: "upload PR Number"
    if: ${{ success() }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: "setup artifact file"
        run: |
          echo "$PR_NUMBER" > prnumber.txt
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: prnumber
          path: prnumber.txt