name: PR Slack Notification

on:
  workflow_run:
    workflows: ["CI"]  # Replace with your CI workflow name
    types:
      - completed

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": ":git: @backend please review [this PR](${{ github.event.pull_request.html_url }}). by ${{ github.event.pull_request.user.login}}. \n
          }' $SLACK_WEBHOOK_URL